// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateTask(arg1:main.CreateTaskRequest):Promise<main.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetAllTasks():Promise<Array<main.Task>>;

export function GetTask(arg1:number):Promise<main.Task>;

export function ToggleTaskDone(arg1:number):Promise<main.Task>;

export function UpdateTask(arg1:main.UpdateTaskRequest):Promise<main.Task>;
